/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.VIEW;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import system.DAO.PedidosDAO;
import system.DTO.PedidosDTO;
import system.DTO.UserDTO;

/**
 *
 * @author igor_
 */
public class DashboardFuncionarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFuncionarioVIEW
     */
    public DashboardFuncionarioVIEW() {
        initComponents();

        setTitle("E-cologic Eletronics");
        setLocationRelativeTo(null);
        listapedidos();
        odernar();
    }
    public int id_sessao;
    public String email_sessao, tipo_sessao;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        email_logado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        total_p = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        total_m = new javax.swing.JLabel();
        total_g = new javax.swing.JLabel();
        total_ids = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        emailuser = new javax.swing.JLabel();
        pedidos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_pedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c_id_pedido = new javax.swing.JTextField();
        c_email_pedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_nome_pedido = new javax.swing.JTextField();
        btn_cadastrar_pedido = new javax.swing.JButton();
        btn_upadate_pedido = new javax.swing.JButton();
        btn_deletar_pedido = new javax.swing.JButton();
        btn_atualiza_pedido = new javax.swing.JButton();
        btn_limpar_pedido = new javax.swing.JButton();
        c_criadopor_pedido = new javax.swing.JTextField();
        cbx_tipo_pedido = new javax.swing.JComboBox<>();
        c_rua_pedido = new javax.swing.JTextField();
        c_cidade_pedido = new javax.swing.JTextField();
        c_numcasa_pedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        c_datacriada_pedido = new javax.swing.JTextField();
        c_datacoleta_pedido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/system/imgs/icon.png")).getImage());

        jTabbedPane2.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        inicio.setBackground(new java.awt.Color(204, 255, 204));

        jLabel21.setText("Painel de Relatorios");

        jButton1.setText("relatorio diario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Total de Pedios:");

        total_p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_p.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel24.setText("Pedidos P:");

        jLabel25.setText("Pedidos M:");

        jLabel26.setText("Pedidos G:");

        total_m.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_m.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        total_g.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_g.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        total_ids.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_ids.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(total_ids, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(total_p, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(total_m, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(total_g, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_p, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_m, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_ids, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(total_g, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Seja Bem-vindo");

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(email_logado, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inicioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(emailuser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23))))
                .addGap(101, 101, 101)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailuser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(email_logado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Inicio", inicio);

        pedidos.setBackground(new java.awt.Color(204, 255, 204));

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        tabela_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "CRIADO", "COLETA","CRIADOPOR","TIPO","RUA","CIDADE","NUMERO"
            }
        ));
        tabela_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_pedidoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela_pedido);

        jLabel10.setText("Nome:");

        jLabel11.setText("Email");

        c_id_pedido.setEnabled(false);
        c_id_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_id_pedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        btn_cadastrar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastrar_pedido.setText("Cadastrar");
        btn_cadastrar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_pedidoActionPerformed(evt);
            }
        });

        btn_upadate_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_upadate_pedido.setText("Upadate");
        btn_upadate_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upadate_pedidoActionPerformed(evt);
            }
        });

        btn_deletar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_deletar_pedido.setText("Deletar");
        btn_deletar_pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_deletar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar_pedidoActionPerformed(evt);
            }
        });

        btn_atualiza_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_atualiza_pedido.setText("Atualizar");
        btn_atualiza_pedido.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_atualiza_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualiza_pedidoActionPerformed(evt);
            }
        });

        btn_limpar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpar_pedido.setText("Limpar");
        btn_limpar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_pedidoActionPerformed(evt);
            }
        });

        c_criadopor_pedido.setEnabled(false);

        cbx_tipo_pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G" }));
        cbx_tipo_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipo_pedidoActionPerformed(evt);
            }
        });

        c_numcasa_pedido.setToolTipText("");

        jLabel12.setText(" Pedido em criado:");

        jLabel13.setText("Data da coleta:");

        jLabel15.setText("Criado por:");

        jLabel16.setText("Tipo de coleta:");

        jLabel17.setText("Rua:");

        jLabel18.setText("Cidade:");

        jLabel19.setText("Número da casa:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Crud Produtos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 135, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(c_nome_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_email_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(c_datacriada_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(c_criadopor_pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(c_id_pedido, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(cbx_tipo_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel18))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(c_rua_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c_cidade_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(c_numcasa_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c_datacoleta_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_atualiza_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_upadate_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_deletar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_cadastrar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_id_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_nome_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_email_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datacriada_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datacoleta_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_deletar_pedido)
                            .addComponent(btn_limpar_pedido))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atualiza_pedido)
                            .addComponent(btn_upadate_pedido))
                        .addGap(17, 17, 17)
                        .addComponent(btn_cadastrar_pedido)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_criadopor_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipo_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_rua_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_cidade_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_numcasa_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout pedidosLayout = new javax.swing.GroupLayout(pedidos);
        pedidos.setLayout(pedidosLayout);
        pedidosLayout.setHorizontalGroup(
            pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pedidosLayout.setVerticalGroup(
            pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Pedidos", pedidos);

        jDesktopPane1.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2AncestorAdded

    private void cbx_tipo_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipo_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tipo_pedidoActionPerformed

    private void btn_limpar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_pedidoActionPerformed
        zerarcampospedidos();
    }//GEN-LAST:event_btn_limpar_pedidoActionPerformed

    private void btn_atualiza_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualiza_pedidoActionPerformed
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_atualiza_pedidoActionPerformed

    private void btn_deletar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar_pedidoActionPerformed
        deletapedido();
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_deletar_pedidoActionPerformed

    private void btn_upadate_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upadate_pedidoActionPerformed
        updatepedido();
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_upadate_pedidoActionPerformed

    private void btn_cadastrar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_pedidoActionPerformed
        cadastrarpedidos();
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_cadastrar_pedidoActionPerformed

    private void c_id_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_id_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_id_pedidoActionPerformed

    private void tabela_pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_pedidoMouseClicked
        carregarcampospedidos();
    }//GEN-LAST:event_tabela_pedidoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ids();
        tipos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFuncionarioVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualiza_pedido;
    private javax.swing.JButton btn_cadastrar_pedido;
    private javax.swing.JButton btn_deletar_pedido;
    private javax.swing.JButton btn_limpar_pedido;
    private javax.swing.JButton btn_upadate_pedido;
    private javax.swing.JTextField c_cidade_pedido;
    private javax.swing.JTextField c_criadopor_pedido;
    private javax.swing.JTextField c_datacoleta_pedido;
    private javax.swing.JTextField c_datacriada_pedido;
    private javax.swing.JTextField c_email_pedido;
    private javax.swing.JTextField c_id_pedido;
    private javax.swing.JTextField c_nome_pedido;
    private javax.swing.JTextField c_numcasa_pedido;
    private javax.swing.JTextField c_rua_pedido;
    private javax.swing.JComboBox<String> cbx_tipo_pedido;
    private javax.swing.JLabel email_logado;
    private javax.swing.JLabel emailuser;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel pedidos;
    private javax.swing.JTable tabela_pedido;
    private javax.swing.JLabel total_g;
    private javax.swing.JLabel total_ids;
    private javax.swing.JLabel total_m;
    private javax.swing.JLabel total_p;
    // End of variables declaration//GEN-END:variables

    public void Pegarid(UserDTO objuserdto) {

        id_sessao = objuserdto.getId_usuario();
        email_sessao = objuserdto.getUser_email();
        tipo_sessao = objuserdto.getUser_tipo();

        emailuser.setText(email_sessao);

    }

    public void odernar() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela_pedido.getModel();
        tabela_pedido.setRowSorter(new TableRowSorter(modelo1));
    }


    /*
    
    Codigo Pedidos
    
     */
    private void cadastrarpedidos() {
        try {
            int criadopor, numcasa;
            String nome, email, datacriada, datacoleta, tipo, rua, cidade;
            nome = c_nome_pedido.getText();
            email = c_email_pedido.getText();
            tipo = cbx_tipo_pedido.getSelectedItem().toString();
            datacriada = c_datacriada_pedido.getText();
            datacoleta = c_datacoleta_pedido.getText();
            criadopor = id_sessao;
            rua = c_rua_pedido.getText();
            cidade = c_cidade_pedido.getText();
            numcasa = Integer.parseInt(c_numcasa_pedido.getText());

            PedidosDTO objpedidosdto = new PedidosDTO();

            objpedidosdto.setNome(nome);
            objpedidosdto.setEmail(email);
            objpedidosdto.setTipo(tipo);
            objpedidosdto.setDatacriada(datacriada);
            objpedidosdto.setDatacoleta(datacoleta);
            objpedidosdto.setCriadopor(criadopor);
            objpedidosdto.setRua(rua);
            objpedidosdto.setCidade(cidade);
            objpedidosdto.setNumcasa(numcasa);

            PedidosDAO objfuncionariodao = new PedidosDAO();
            objfuncionariodao.cadastropedidos(objpedidosdto);

        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campos não podem ser vazio!");
        }
    }

    private void carregarcampospedidos() {
        try {
            int linha = tabela_pedido.getSelectedRow();

            c_id_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 0).toString());
            c_nome_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 1).toString());
            c_email_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 2).toString());
            c_datacriada_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 3).toString());
            c_datacoleta_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 4).toString());
            c_criadopor_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 5).toString());
            cbx_tipo_pedido.setSelectedItem(tabela_pedido.getModel().getValueAt(linha, 6).toString());
            c_rua_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 7).toString());
            c_cidade_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 8).toString());
            c_numcasa_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 9).toString());

            c_datacoleta_pedido.setEnabled(false);
            c_datacriada_pedido.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException | java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha válida da tabela");
        }
    }

    private void listapedidos() {
        try {
            PedidosDAO objpedidosdao = new PedidosDAO();
            DefaultTableModel model = (DefaultTableModel) tabela_pedido.getModel();
            model.setNumRows(0);

            ArrayList<PedidosDTO> lista = objpedidosdao.listarpedidos();
            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getEmail(),
                    lista.get(i).getDatacriada(),
                    lista.get(i).getDatacoleta(),
                    lista.get(i).getCriadopor(),
                    lista.get(i).getTipo(),
                    lista.get(i).getRua(),
                    lista.get(i).getCidade(),
                    lista.get(i).getNumcasa()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listapedidos: " + erro);
        }
    }

    private void updatepedido() {
        try {
            int id, criadopor, numcasa;
            String nome, email, datacriada, datacoleta, tipo, rua, cidade;
            id = Integer.parseInt(c_id_pedido.getText());
            nome = c_nome_pedido.getText();
            email = c_email_pedido.getText();
            tipo = cbx_tipo_pedido.getSelectedItem().toString();
            datacriada = c_datacriada_pedido.getText();
            datacoleta = c_datacoleta_pedido.getText();
            criadopor = id_sessao;
            rua = c_rua_pedido.getText();
            cidade = c_cidade_pedido.getText();
            numcasa = Integer.parseInt(c_numcasa_pedido.getText());

            PedidosDTO objpedidosdto = new PedidosDTO();

            objpedidosdto.setId(id);
            objpedidosdto.setNome(nome);
            objpedidosdto.setEmail(email);
            objpedidosdto.setTipo(tipo);
            objpedidosdto.setDatacriada(datacriada);
            objpedidosdto.setDatacoleta(datacoleta);
            objpedidosdto.setCriadopor(criadopor);
            objpedidosdto.setRua(rua);
            objpedidosdto.setCidade(cidade);
            objpedidosdto.setNumcasa(numcasa);

            PedidosDAO objfuncionariodao = new PedidosDAO();
            objfuncionariodao.updatepedido(objpedidosdto);

        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Selecione um pedido para alterar!");
        }
    }

    private void deletapedido() {
        try {
            int id;
            id = Integer.parseInt(c_id_pedido.getText());

            PedidosDTO objpedidosdto = new PedidosDTO();
            objpedidosdto.setId(id);

            PedidosDAO objpedidosdao = new PedidosDAO();
            objpedidosdao.deletapedido(objpedidosdto);

        } catch (java.lang.NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Selecione um pedido para deletar!");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listapedidos: " + erro);
        }
    }

    private void zerarcampospedidos() {

        c_datacoleta_pedido.setEnabled(true);
        c_datacriada_pedido.setEnabled(true);

        c_id_pedido.setText("");
        c_nome_pedido.setText("");
        c_email_pedido.setText("");
        c_datacriada_pedido.setText("");
        c_datacoleta_pedido.setText("");
        c_criadopor_pedido.setText("");
        c_rua_pedido.setText("");
        c_cidade_pedido.setText("");
        c_numcasa_pedido.setText("");
        cbx_tipo_pedido.setSelectedItem("P");
    }

    public void ids() {

        try {
            PedidosDAO objpedidosdao = new PedidosDAO();
            ResultSet rs = objpedidosdao.totalid();
            int ids, n_ids = 0;
            while (rs.next()) {
                ids = rs.getInt("id");
                n_ids += 1;
            }
            total_ids.setText(Integer.toString(n_ids));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Inicio função: " + erro);
        }

    }

    public void tipos() {

        try {
            PedidosDAO objpedidosdao = new PedidosDAO();
            ResultSet rs = objpedidosdao.tipos();
            int p = 0, m = 0, g = 0;
            String tipo;
            while (rs.next()) {
                tipo = rs.getString("type_pedido");
                System.out.println(tipo);
                if ("P".equals(tipo)) {
                    p += 1;
                } else if ("M".equals(tipo)) {
                    m += 1;
                } else {
                    g += 1;
                }
            }
            total_p.setText(Integer.toString(p));
            total_m.setText(Integer.toString(m));
            total_g.setText(Integer.toString(g));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Inicio função: " + erro);
        }

    }

}
