/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.VIEW;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import system.DAO.FuncionarioDAO;
import system.DAO.PedidosDAO;
import system.DTO.FuncionarioDTO;
import system.DTO.PedidosDTO;
import system.DTO.UserDTO;

/**
 *
 * @author igor_
 */
public class DashboardADMVIEW extends javax.swing.JFrame {

    /**
     * Creates new form DashboardVIEW
     */
    public DashboardADMVIEW() {
        initComponents();
        setTitle("E-cologic Eletronics");
        setLocationRelativeTo(null);
        listafuncionarios();
        listapedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        email_logado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_pedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c_id_pedido = new javax.swing.JTextField();
        c_email_pedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_nome_pedido = new javax.swing.JTextField();
        btn_cadastrar_pedido = new javax.swing.JButton();
        btn_upadate_pedido = new javax.swing.JButton();
        btn_deletar_pedido = new javax.swing.JButton();
        btn_atualiza_pedido = new javax.swing.JButton();
        btn_limpar_pedido = new javax.swing.JButton();
        c_criadopor_pedido = new javax.swing.JTextField();
        cbx_tipo_pedido = new javax.swing.JComboBox<>();
        c_rua_pedido = new javax.swing.JTextField();
        c_cidade_pedido = new javax.swing.JTextField();
        c_numcasa_pedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        c_datacriada_pedido = new javax.swing.JTextField();
        c_datacoleta_pedido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_funcionario = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        c_email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_senha = new javax.swing.JPasswordField();
        btn_cadastrar = new javax.swing.JButton();
        btn_upadate = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        cbx_tipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/system/imgs/icon.png")).getImage());

        jTabbedPane2.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(email_logado, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 610, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(email_logado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 509, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Inicio", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        tabela_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "CRIADO", "COLETA","CRIADOPOR","TIPO","RUA","CIDADE","NUMERO"
            }
        ));
        tabela_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_pedidoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela_pedido);

        jLabel10.setText("Nome:");

        jLabel11.setText("Email");

        c_id_pedido.setEnabled(false);
        c_id_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_id_pedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        btn_cadastrar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastrar_pedido.setText("Cadastrar");
        btn_cadastrar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_pedidoActionPerformed(evt);
            }
        });

        btn_upadate_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_upadate_pedido.setText("Upadate");
        btn_upadate_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upadate_pedidoActionPerformed(evt);
            }
        });

        btn_deletar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_deletar_pedido.setText("Deletar");
        btn_deletar_pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_deletar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar_pedidoActionPerformed(evt);
            }
        });

        btn_atualiza_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_atualiza_pedido.setText("Atualizar");
        btn_atualiza_pedido.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_atualiza_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualiza_pedidoActionPerformed(evt);
            }
        });

        btn_limpar_pedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpar_pedido.setText("Limpar");
        btn_limpar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_pedidoActionPerformed(evt);
            }
        });

        c_criadopor_pedido.setEnabled(false);

        cbx_tipo_pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G" }));
        cbx_tipo_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipo_pedidoActionPerformed(evt);
            }
        });

        c_numcasa_pedido.setToolTipText("");

        jLabel12.setText(" Pedido em criado:");

        jLabel13.setText("Data da coleta:");

        jLabel15.setText("Criado por:");

        jLabel16.setText("Tipo de coleta:");

        jLabel17.setText("Rua:");

        jLabel18.setText("Cidade:");

        jLabel19.setText("Número da casa:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Crud Produtos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 115, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(c_nome_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_email_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(c_datacriada_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(c_criadopor_pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(c_id_pedido, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(cbx_tipo_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel18))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(c_rua_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c_cidade_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(c_numcasa_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c_datacoleta_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_atualiza_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_upadate_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_deletar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_cadastrar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_id_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_nome_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_email_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datacriada_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datacoleta_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_deletar_pedido)
                            .addComponent(btn_limpar_pedido))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atualiza_pedido)
                            .addComponent(btn_upadate_pedido))
                        .addGap(17, 17, 17)
                        .addComponent(btn_cadastrar_pedido)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_criadopor_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipo_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_rua_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_cidade_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_numcasa_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Pedidos", jPanel5);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        tabela_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "SENHA", "TIPO"
            }
        ));
        tabela_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_funcionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_funcionario);

        jLabel6.setText("NOME:");

        jLabel7.setText("EMAIL:");

        jLabel8.setText("TIPO DE ACESSO:");

        c_id.setEnabled(false);

        jLabel1.setText("ID:");

        jLabel2.setText("SENHA:");

        btn_cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_upadate.setBackground(new java.awt.Color(255, 255, 255));
        btn_upadate.setText("Upadate");
        btn_upadate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upadateActionPerformed(evt);
            }
        });

        btn_deletar.setBackground(new java.awt.Color(255, 255, 255));
        btn_deletar.setText("Deletar");
        btn_deletar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_atualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_limpar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ADM", "FUNCIONARIO" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Crud funcionarios/administradores");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_upadate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(83, 83, 83))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deletar)
                    .addComponent(btn_limpar)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atualizar)
                            .addComponent(btn_upadate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(btn_cadastrar)))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(25, 25, 25)))
                        .addGap(31, 31, 31)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Funcionarios", jPanel4);

        jDesktopPane1.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_pedidoActionPerformed
        zerarcampospedidos();
    }//GEN-LAST:event_btn_limpar_pedidoActionPerformed

    private void btn_atualiza_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualiza_pedidoActionPerformed
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_atualiza_pedidoActionPerformed

    private void btn_deletar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar_pedidoActionPerformed

    }//GEN-LAST:event_btn_deletar_pedidoActionPerformed

    private void btn_upadate_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upadate_pedidoActionPerformed

    }//GEN-LAST:event_btn_upadate_pedidoActionPerformed

    private void btn_cadastrar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_pedidoActionPerformed
        cadastrarpedidos();
        listapedidos();
        zerarcampospedidos();
    }//GEN-LAST:event_btn_cadastrar_pedidoActionPerformed

    private void tabela_pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_pedidoMouseClicked
        carregarcampospedidos();
    }//GEN-LAST:event_tabela_pedidoMouseClicked

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        zerarcampos();
        listafuncionarios();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        listafuncionarios();
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        deletafuncionario();
        listafuncionarios();
        zerarcampos();
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_upadateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upadateActionPerformed
        updatefuncionario();
        listafuncionarios();
        zerarcampos();
    }//GEN-LAST:event_btn_upadateActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        cadastrarfuncionario();
        listafuncionarios();
        zerarcampos();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void tabela_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_funcionarioMouseClicked
        carregarcampos();
    }//GEN-LAST:event_tabela_funcionarioMouseClicked

    private void c_id_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_id_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_id_pedidoActionPerformed

    private void cbx_tipo_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipo_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tipo_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardADMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardADMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardADMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardADMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardADMVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualiza_pedido;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cadastrar_pedido;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_deletar_pedido;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_limpar_pedido;
    private javax.swing.JButton btn_upadate;
    private javax.swing.JButton btn_upadate_pedido;
    private javax.swing.JTextField c_cidade_pedido;
    private javax.swing.JTextField c_criadopor_pedido;
    private javax.swing.JTextField c_datacoleta_pedido;
    private javax.swing.JTextField c_datacriada_pedido;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_email_pedido;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_id_pedido;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_nome_pedido;
    private javax.swing.JTextField c_numcasa_pedido;
    private javax.swing.JTextField c_rua_pedido;
    private javax.swing.JPasswordField c_senha;
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JComboBox<String> cbx_tipo_pedido;
    private javax.swing.JLabel email_logado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tabela_funcionario;
    private javax.swing.JTable tabela_pedido;
    // End of variables declaration//GEN-END:variables
    public int id_sessao;
    public String email_sessao;

    public void Pegarid(UserDTO objuserdto) {

        int id_sessao = objuserdto.getId_usuario();
        String email_sessao = objuserdto.getUser_email();

        email_logado.setText("User logado : " + email_sessao);

    }

    private void carregarcampos() {
        try {
            int linha = tabela_funcionario.getSelectedRow();
            c_id.setText(tabela_funcionario.getModel().getValueAt(linha, 0).toString());
            c_nome.setText(tabela_funcionario.getModel().getValueAt(linha, 1).toString());
            c_email.setText(tabela_funcionario.getModel().getValueAt(linha, 2).toString());
            c_senha.setText(tabela_funcionario.getModel().getValueAt(linha, 3).toString());
            cbx_tipo.setSelectedItem(tabela_funcionario.getModel().getValueAt(linha, 4).toString());
        } catch (ArrayIndexOutOfBoundsException | java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha válida da tabela");
        }
    }

    private void cadastrarfuncionario() {
        String nome, email, senha, tipo;

        nome = c_nome.getText();
        email = c_email.getText();
        senha = c_senha.getText();
        tipo = cbx_tipo.getSelectedItem().toString();

        FuncionarioDTO objfuncionariodto = new FuncionarioDTO();
        objfuncionariodto.setNome(nome);
        objfuncionariodto.setEmail(email);
        objfuncionariodto.setSenha(senha);
        objfuncionariodto.setTipo(tipo);

        FuncionarioDAO objfuncionariodao = new FuncionarioDAO();
        objfuncionariodao.cadastrofuncionario(objfuncionariodto);

    }

    private void listafuncionarios() {
        try {
            FuncionarioDAO objfuncionariodao = new FuncionarioDAO();
            DefaultTableModel model = (DefaultTableModel) tabela_funcionario.getModel();
            model.setNumRows(0);

            ArrayList<FuncionarioDTO> lista = objfuncionariodao.listarfuncionario();

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getEmail(),
                    lista.get(i).getSenha(),
                    lista.get(i).getTipo()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listafuncionarios: " + erro);
        }
    }

    private void updatefuncionario() {
        try {
            int id;
            String nome, email, senha, tipo;

            id = Integer.parseInt(c_id.getText());
            nome = c_nome.getText();
            email = c_email.getText();
            senha = c_senha.getText();
            tipo = cbx_tipo.getSelectedItem().toString();

            FuncionarioDTO objfuncionariodto = new FuncionarioDTO();
            objfuncionariodto.setId(id);
            objfuncionariodto.setNome(nome);
            objfuncionariodto.setEmail(email);
            objfuncionariodto.setSenha(senha);
            objfuncionariodto.setTipo(tipo);

            FuncionarioDAO objfuncionariodao = new FuncionarioDAO();
            objfuncionariodao.updatefuncionario(objfuncionariodto);

        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario para alterar!");
        }
    }

    private void deletafuncionario() {
        try {
            int id;

            id = Integer.parseInt(c_id.getText());

            FuncionarioDTO objfuncionariodto = new FuncionarioDTO();
            objfuncionariodto.setId(id);

            FuncionarioDAO objfuncionariodao = new FuncionarioDAO();
            objfuncionariodao.deletafuncionario(objfuncionariodto);

        } catch (java.lang.NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario para deletar!");
        }
    }

    private void zerarcampos() {
        c_id.setText("");
        c_nome.setText("");
        c_email.setText("");
        c_senha.setText("");
        cbx_tipo.setSelectedItem("Selecione");
    }

    /*
    
    Codigo Pedidos
    
     */
    private void cadastrarpedidos() {
        int criadopor, numcasa;
        String nome, email, datacriada, datacoleta, tipo, rua, cidade;
        nome = c_nome_pedido.getText();
        email = c_email_pedido.getText();
        tipo = cbx_tipo_pedido.getSelectedItem().toString();
        datacriada = c_datacriada_pedido.getText();
        datacoleta = c_datacoleta_pedido.getText();
        criadopor = id_sessao;
        rua = c_rua_pedido.getText();
        cidade = c_cidade_pedido.getText();
        numcasa = Integer.parseInt(c_numcasa_pedido.getText());

        PedidosDTO objpedidosdto = new PedidosDTO();
        objpedidosdto.setNome(nome);
        objpedidosdto.setEmail(email);
        objpedidosdto.setTipo(tipo);
        objpedidosdto.setDatacriada(datacriada);
        objpedidosdto.setDatacoleta(datacoleta);
        objpedidosdto.setCriadopor(criadopor);
        objpedidosdto.setRua(rua);
        objpedidosdto.setCidade(cidade);
        objpedidosdto.setNumcasa(numcasa);

        PedidosDAO objfuncionariodao = new PedidosDAO();
        objfuncionariodao.cadastropedidos(objpedidosdto);

    }

    private void carregarcampospedidos() {
        try {
            int linha = tabela_pedido.getSelectedRow();

            c_id_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 0).toString());
            c_nome_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 1).toString());
            c_email_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 2).toString());
            c_datacriada_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 3).toString());
            c_datacoleta_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 4).toString());
            c_criadopor_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 5).toString());
            cbx_tipo_pedido.setSelectedItem(tabela_pedido.getModel().getValueAt(linha, 6).toString());
            c_rua_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 7).toString());
            c_cidade_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 8).toString());
            c_numcasa_pedido.setText(tabela_pedido.getModel().getValueAt(linha, 9).toString());

            c_datacoleta_pedido.setEnabled(false);
            c_datacriada_pedido.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException | java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha válida da tabela");
        }
    }

    private void listapedidos() {
        try {
            PedidosDAO objpedidosdao = new PedidosDAO();
            DefaultTableModel model = (DefaultTableModel) tabela_pedido.getModel();
            model.setNumRows(0);

            ArrayList<PedidosDTO> lista = objpedidosdao.listarpedidos();
            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getEmail(),
                    lista.get(i).getDatacriada(),
                    lista.get(i).getDatacoleta(),
                    lista.get(i).getCriadopor(),
                    lista.get(i).getTipo(),
                    lista.get(i).getRua(),
                    lista.get(i).getCidade(),
                    lista.get(i).getNumcasa()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listapedidos: " + erro);
        }
    }

    private void zerarcampospedidos() {

        c_datacoleta_pedido.setEnabled(true);
        c_datacriada_pedido.setEnabled(true);

        c_id_pedido.setText("");
        c_nome_pedido.setText("");
        c_email_pedido.setText("");
        c_datacriada_pedido.setText("");
        c_datacoleta_pedido.setText("");
        c_criadopor_pedido.setText("");
        c_rua_pedido.setText("");
        c_cidade_pedido.setText("");
        c_numcasa_pedido.setText("");
        cbx_tipo_pedido.setSelectedItem("P");
    }

}
